# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-19 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CONFERENCE',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=20)),
                ('sex', models.IntegerField(db_column='sex', default=0)),
                ('cardid', models.CharField(db_column='cardid', max_length=20, null=True)),
                ('company', models.CharField(db_column='company', max_length=50, null=True)),
                ('department', models.CharField(db_column='department', max_length=20, null=True)),
                ('degree', models.CharField(db_column='degree', max_length=10, null=True)),
                ('title', models.CharField(db_column='title', max_length=20, null=True)),
                ('post', models.CharField(db_column='post', max_length=20, null=True)),
                ('phone', models.CharField(db_column='phone', max_length=11, null=True)),
                ('registtime', models.DateField(blank=True, db_column='registtime', null=True)),
                ('pay', models.IntegerField(db_column='pay', null=True)),
                ('banknum', models.CharField(db_column='banknum', max_length=19, null=True)),
                ('bankname', models.CharField(db_column='bankname', max_length=30, null=True)),
                ('room', models.CharField(db_column='room', max_length=10, null=True)),
                ('hoteldays', models.IntegerField(db_column='hoteldays', null=True)),
                ('ticketnum', models.CharField(db_column='ticketnum', max_length=20, null=True)),
                ('score', models.CharField(db_column='score', max_length=20, null=True)),
            ],
            options={
                'db_table': 'conference',
            },
        ),
    ]
